# Generated by Django 3.1.2 on 2021-01-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_essential_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essential_details',
            name='no_of_orders',
            field=models.IntegerField(default=0),
        ),
    ]
